Algoritmo "semnome"

Var
procedimento msg(vt: real)
             Inicio
             escreval("--------------")
             escreval("Item adicionado")
             escreval("Valor total", vt)
             escreval("--------------")
             
             se (vt = 100) entao
             escreval("Esse trem é 100")
             fimse
fimProcedimento

Inicio
msg(54)
msg(4)
msg(5)
msg(100)
msg(463)


Fimalgoritmo