Algoritmo "recepcao"

Var
nome, email : caractere
idade : inteiro

Inicio
escreval("Boa tarde! Digite o seu nome: ")
leia(nome)

limpaTela()

escreval("Digite o sua idade: ")
leia(idade)

limpaTela()

escreval("Digite o sua email: ")
leia(email)

limpaTela()

escreval("Cadastro efetuado com sucesso!")
escreval("*******************")
escreval("Usuario : ", nome)
escreval("Idade : ", idade)
escreval("Email : ", email)
escreval("*******************")
Fimalgoritmo