Algoritmo "estrutura de repeticao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/10/2024
Var
usuarioC, login, senhaC, usuario, senha : caractere


Inicio
usuarioC <- "adm"
senhaC <- "umasenhaincrivel"

// while
enquanto (login = "incorreto") faca
   leia(usuario)
   leia(senha)
fimEnquanto


Fimalgoritmo